[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://store-ledger-api.up.railway.app/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://store-ledger-api.up.railway.app/api"