services:
  - type: web
    name: store-ledger-backend
    env: node
    rootDir: project/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://ineverydomain:<db_password>@cluster0.m6fgmt1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  - type: web
    name: store-ledger-frontend
    env: static
    rootDir: project
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://store-ledger-backend.onrender.com
